version: '3'

tasks:
  default:
    cmds:
      - task --list
  setup:
    desc: install all the required dependencies for prestagri
    cmds:
      - cd backend && uv install
      - cd frontend && npm install
  serve_api:
    desc: serve
    dir: backend
    cmds:
      - uv run fastapi dev
  scalingo:
    desc: serve as scalingo would
    dir: backend
    cmds: 
      - uv run uvicorn app.main:app --host 0.0.0.0 --port 8000
  serve_front:
    desc: run the doc locally
    cmds:
      - cd frontend && npm run start
  doc_read:
    desc: serve the doc locally with the search option
    cmds:
      - cd frontend && npm run build  && http-server dist -p 4444
  update_backend_catala:
    desc: build catala code and add the generated source to the python library
    cmds:
      - cd catala && clerk build
      - mv catala/_target/prestagri_catala/python/* backend/app/catala/generated
      - find backend/app/catala/generated/*.py -type f -exec sed -i 's/catala_runtime/.catala_runtime/g' {} +
      - sed -i 's/import dates/from .dates import */g' backend/app/catala/generated/catala_runtime.py
      - sed -i 's/dates\.//g' backend/app/catala/generated/catala_runtime.py
