version: '3'

tasks:
  default:
    cmds:
      - task --list
  setup:
    desc: install all the required dependencies for prestagri
    cmds:
      - pre-commit install
      - cd backend && uv install
      - cd frontend && npm install
  test:
    desc: run backend unit test
    dir: backend
    cmds:
      - uv run python -m pytest
  serve_api:
    desc: serve
    dir: backend
    cmds:
      - uv run fastapi dev
  scalingo:
    desc: serve as scalingo would
    dir: backend
    cmds:
      - uv run uvicorn app.main:app --host 0.0.0.0 --port 8000
  serve_front:
    desc: run the doc locally
    cmds:
      - cd frontend && npm run start
  check:
    desc: run pre-commit hook
    cmds:
      - pre-commit run --all-files
  doc_read:
    desc: serve the doc locally with the search option
    cmds:
      - cd frontend && npm run build  && http-server dist -p 4444
  update_backend_catala:
    desc: build catala code and add the generated source to the python library

    cmds:
      - cd catala && clerk build
      - rm -r backend/app/catala/generated && mkdir backend/app/catala/generated
      - mv catala/_build/libcatala/python/* backend/app/catala/generated
      - mv catala/_target/prestagri_catala/python/* backend/app/catala/generated
      - find backend/app/catala/generated/*.py -type f -exec sed -i 's/catala_runtime/\.catala_runtime/g' {} +
      - sed -i 's/import dates/from .dates import */g' backend/app/catala/generated/catala_runtime.py
      - sed -i 's/(etudiants_fiscalement_independants.length() > Integer(0))/(len(etudiants_fiscalement_independants) > 0)/g' backend/app/catala/generated/Aide_scolarite.py
      - sed -i 's/criteres_applicables_garde_alternee.map(nombre_unites__1)/map(nombre_unites__1, criteres_applicables_garde_alternee)/g' backend/app/catala/generated/Quotient_familial.py
      - sed -i 's/menage__1.membres_du_foyer.map(revenu_total__1)/map(revenu_total__1, menage__1.membres_du_foyer)/g' backend/app/catala/generated/Quotient_familial.py
      - sed -i 's/menage__1.membres_du_foyer.map(nombre_personnes_vivants_au_foyer__1)/map(nombre_personnes_vivants_au_foyer__1, menage__1.membres_du_foyer)/g' backend/app/catala/generated/Quotient_familial.py

      - sed -i "s/l.fold_left(somme__1, Decimal('0'))/sum(l)/g" backend/app/catala/generated/Decimal_fr.py
      - sed -i "s/l.fold_left(somme__1, Integer(0))/sum(l)/g" backend/app/catala/generated/Integer_fr.py
      - sed -i "s/l.fold_left(somme__1, Money('0.00'))/sum(l)/g" backend/app/catala/generated/Money_fr.py


      - sed -i 's/dates\.//g' backend/app/catala/generated/catala_runtime.py
  setup_commit:
    desc: use production url when commiting
    cmds:
      - sed -i 's/http:\/\/localhost:8000/https:\/\/api.prest-agri.beta.gouv.fr/g' frontend/src/pages/aide_scolarite.astro
      - sed -i 's/http:\/\/localhost:8000/https:\/\/api.prest-agri.beta.gouv.fr/g' frontend/src/pages/quotient_familial.astro
  setup_local:
    desc: use localhost url when dev
    cmds:
      - sed -i 's/https:\/\/api.prest-agri.beta.gouv.fr/http:\/\/localhost:8000/g' frontend/src/pages/aide_scolarite.astro
      - sed -i 's/https:\/\/api.prest-agri.beta.gouv.fr/http:\/\/localhost:8000/g' frontend/src/pages/quotient_familial.astro
