version: '3'

tasks:
  default:
    cmds:
      - task --list
  setup:
    desc: install all the required dependencies for prestagri
    cmds:
      - cd backend && poetry install
      - cd doc && npm install
  serve:
    desc: serve
    dir: backend
    cmds:
      - poetry run fastapi dev
  doc:
    desc: run the doc locally
    cmds:
      - cd doc && npm run start
  doc_read:
    desc: serve the doc locally with the search option
    cmds:
      - cd doc && npm run build > /dev/null && http-server dist -p 4444

