[project]
include_dirs = [ 
    "src/aide_scolarite",
    "src/commun",
    "src/commun/structures"
] 
build_dir    = "_build"    # Définit où sortir les fichiers compilés générés.
target_dir   = "_target"   # Définit où sortir les fichiers finaux des cibles.

# Chaque section [[target]] décrit une cible de construction pour le projet

[[target]]
name     = "quotient_famillial"
modules  = [ "Quotient_familial"]
tests    = [ "tests/tests_quotient_familial.catala_fr" ]
backends = [ "python" ]

[[target]]
name     = "aide_scolarite"
modules  = [ "Aide_scolarite"]
tests    = [ "tests/tests_aide_scolarite.catala_fr" ]
backends = [ "python" ]

[[target]]
name     = "structures"
modules  = ["Famille", "P"]
tests    = [ ]
backends = [ "python" ]
