[project]
include_dirs = [ "src/commun"] 
build_dir    = "_build"    # Définit où sortir les fichiers compilés générés.
target_dir   = "_target"   # Définit où sortir les fichiers finaux des cibles.

# Chaque section [[target]] décrit une cible de construction pour le projet

[[target]]
name     = "quotient_famillial"
modules  = [ "Quotient_familial"]
tests    = [ "tests/tests_quotient_familial.catala_fr" ]
backends = [ "python" ]

[[target]]
name     = "famille"
modules  = ["Famille", "Personne"]
tests    = [ ]
backends = [ "python" ]