# This file has been generated by the Catala compiler, do not edit!

from .catala_runtime import *
from typing import Any, List, Callable, Tuple
from enum import Enum
from . import Date_internal as date_internal
from . import List_internal as list_internal
from . import List_fr as list_fr

class Mois_Code(Enum):
    Janvier = 0
    Fevrier = 1
    Mars = 2
    Avril = 3
    Mai = 4
    Juin = 5
    Juillet = 6
    Aout = 7
    Septembre = 8
    Octobre = 9
    Novembre = 10
    Decembre = 11

class Mois:
    def __init__(self, code: Mois_Code, value: Any) -> None:
        self.code = code
        self.value = value


    def __eq__(self, other: object) -> bool:
        if isinstance(other, Mois):
            return self.code == other.code and self.value == other.value
        else:
            return False


    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "{}({})".format(self.code, self.value)

class JourDeLaSemaine_Code(Enum):
    Lundi = 0
    Mardi = 1
    Mercredi = 2
    Jeudi = 3
    Vendredi = 4
    Samedi = 5
    Dimanche = 6

class JourDeLaSemaine:
    def __init__(self, code: JourDeLaSemaine_Code, value: Any) -> None:
        self.code = code
        self.value = value


    def __eq__(self, other: object) -> bool:
        if isinstance(other, JourDeLaSemaine):
            return self.code == other.code and self.value == other.value
        else:
            return False


    def __ne__(self, other: object) -> bool:
        return not (self == other)

    def __str__(self) -> str:
        return "{}({})".format(self.code, self.value)


def min(d1:Date, d2:Date):
    if (d1 <= d2):
        min__1 = (d1)
    else:
        min__1 = (d2)
    return min__1

def max(d1:Date, d2:Date):
    if (d1 >= d2):
        max__1 = (d1)
    else:
        max__1 = (d2)
    return max__1

def depuis_annee_mois_jour(pos:SourcePosition, dannee:Integer, dmois:Integer, djour:Integer):
    return date_internal.of_ymd(pos, dannee, dmois, djour)

def vers_annee_mois_jour(d:Date):
    return date_internal.to_ymd(d)

def dernier_jour_du_mois(d:Date):
    return date_internal.last_day_of_month(d)

def mois_vers_entier(m:Mois):
    if m.code == Mois_Code.Janvier:
        mois_vers_entier__1 = (Integer(1))
    elif m.code == Mois_Code.Fevrier:
        mois_vers_entier__1 = (Integer(2))
    elif m.code == Mois_Code.Mars:
        mois_vers_entier__1 = (Integer(3))
    elif m.code == Mois_Code.Avril:
        mois_vers_entier__1 = (Integer(4))
    elif m.code == Mois_Code.Mai:
        mois_vers_entier__1 = (Integer(5))
    elif m.code == Mois_Code.Juin:
        mois_vers_entier__1 = (Integer(6))
    elif m.code == Mois_Code.Juillet:
        mois_vers_entier__1 = (Integer(7))
    elif m.code == Mois_Code.Aout:
        mois_vers_entier__1 = (Integer(8))
    elif m.code == Mois_Code.Septembre:
        mois_vers_entier__1 = (Integer(9))
    elif m.code == Mois_Code.Octobre:
        mois_vers_entier__1 = (Integer(10))
    elif m.code == Mois_Code.Novembre:
        mois_vers_entier__1 = (Integer(11))
    elif m.code == Mois_Code.Decembre:
        mois_vers_entier__1 = (Integer(12))
    return mois_vers_entier__1

def entier_vers_mois(pos:SourcePosition, i:Integer):
    if (i == Integer(1)):
        entier_vers_mois__1 = (Mois(Mois_Code.Janvier, Unit()))
    elif (i == Integer(2)):
        entier_vers_mois__1 = (Mois(Mois_Code.Fevrier, Unit()))
    elif (i == Integer(3)):
        entier_vers_mois__1 = (Mois(Mois_Code.Mars, Unit()))
    elif (i == Integer(4)):
        entier_vers_mois__1 = (Mois(Mois_Code.Avril, Unit()))
    elif (i == Integer(5)):
        entier_vers_mois__1 = (Mois(Mois_Code.Mai, Unit()))
    elif (i == Integer(6)):
        entier_vers_mois__1 = (Mois(Mois_Code.Juin, Unit()))
    elif (i == Integer(7)):
        entier_vers_mois__1 = (Mois(Mois_Code.Juillet, Unit()))
    elif (i == Integer(8)):
        entier_vers_mois__1 = (Mois(Mois_Code.Aout, Unit()))
    elif (i == Integer(9)):
        entier_vers_mois__1 = (Mois(Mois_Code.Septembre, Unit()))
    elif (i == Integer(10)):
        entier_vers_mois__1 = (Mois(Mois_Code.Octobre, Unit()))
    elif (i == Integer(11)):
        entier_vers_mois__1 = (Mois(Mois_Code.Novembre, Unit()))
    elif (i == Integer(12)):
        entier_vers_mois__1 = (Mois(Mois_Code.Decembre, Unit()))
    else:
        erreur = (date_internal.of_ymd(pos, Integer(-1), Integer(-1), Integer(-1)))
        pos__1 = (SourcePosition(filename="libcatala/date_fr.catala_fr", start_line=172, start_column=65, end_line=172, end_column=75, law_headings=["Mois nommés", "Dates"]))
        raise Impossible(pos__1, None)
    return entier_vers_mois__1

def est_assez_age_arrondi_inferieur(date_de_naissance:Date, age:Duration, a_date:Date):
    return (a_date >= date_internal.add_rounded_down(date_de_naissance, age))

def est_assez_age_arrondi_superieur(date_de_naissance:Date, age:Duration, a_date:Date):
    return (a_date >= date_internal.add_rounded_up(date_de_naissance, age))

def dernier_jour_de_l_annee(d:Date):
    ymd = (vers_annee_mois_jour(d))
    pos = (SourcePosition(filename="libcatala/date_fr.catala_fr", start_line=112, start_column=5, end_line=112, end_column=27, law_headings=["Aller vers le passé ou le futur", "Dates"]))
    return depuis_annee_mois_jour(pos, ymd[0], Integer(12), Integer(31))

def premier_jour_de_l_annee(d:Date):
    ymd = (vers_annee_mois_jour(d))
    pos = (SourcePosition(filename="libcatala/date_fr.catala_fr", start_line=103, start_column=5, end_line=103, end_column=27, law_headings=["Aller vers le passé ou le futur", "Dates"]))
    return depuis_annee_mois_jour(pos, ymd[0], Integer(1), Integer(1))

def premier_jour_du_mois(d:Date):
    ymd = (vers_annee_mois_jour(d))
    pos = (SourcePosition(filename="libcatala/date_fr.catala_fr", start_line=86, start_column=5, end_line=86, end_column=27, law_headings=["Aller vers le passé ou le futur", "Dates"]))
    return depuis_annee_mois_jour(pos, ymd[0], ymd[1], Integer(1))

def acces_jour(d:Date):
    return vers_annee_mois_jour(d)[2]

def acces_mois(d:Date):
    return vers_annee_mois_jour(d)[1]

def acces_annee(d:Date):
    return vers_annee_mois_jour(d)[0]

def est_assez_jeune_arrondi_inferieur(date_de_naissance:Date, age:Duration, a_date:Date):
    return not est_assez_age_arrondi_inferieur(date_de_naissance, age, a_date)

def est_assez_jeune_arrondi_superieur(date_de_naissance:Date, age:Duration, a_date:Date):
    return not est_assez_age_arrondi_superieur(date_de_naissance, age, a_date)

def jour_de_la_semaine(date_donnee:Date):
    month_number = (acces_mois(date_donnee))
    if (month_number < Integer(3)):
        year_number = ((acces_annee(date_donnee) - Integer(1)))
    else:
        year_number = (acces_annee(date_donnee))
    n_number__1 = (list_fr.nieme_element([Integer(0), Integer(3), Integer(2), Integer(5), Integer(0), Integer(3), Integer(5), Integer(1), Integer(4), Integer(6), Integer(2), Integer(4)], month_number))
    if n_number__1.value is not None:
        n_number = (n_number__1.value)
    else:
        pos = (SourcePosition(filename="libcatala/date_fr.catala_fr", start_line=273, start_column=16, end_line=273, end_column=26, law_headings=["Détermination du jour de la semaine d'une date donnée (algorithme de Sakamoto)", "Dates"]))
        raise Impossible(pos, None)
    pos = (SourcePosition(filename="libcatala/date_fr.catala_fr", start_line=277, start_column=31, end_line=277, end_column=32, law_headings=["Détermination du jour de la semaine d'une date donnée (algorithme de Sakamoto)", "Dates"]))
    pos__1 = (SourcePosition(filename="libcatala/date_fr.catala_fr", start_line=278, start_column=31, end_line=278, end_column=32, law_headings=["Détermination du jour de la semaine d'une date donnée (algorithme de Sakamoto)", "Dates"]))
    pos__2 = (SourcePosition(filename="libcatala/date_fr.catala_fr", start_line=279, start_column=31, end_line=279, end_column=32, law_headings=["Détermination du jour de la semaine d'une date donnée (algorithme de Sakamoto)", "Dates"]))
    pos__3 = (SourcePosition(filename="libcatala/date_fr.catala_fr", start_line=284, start_column=33, end_line=284, end_column=34, law_headings=["Détermination du jour de la semaine d'une date donnée (algorithme de Sakamoto)", "Dates"]))
    pos__4 = (SourcePosition(filename="libcatala/date_fr.catala_fr", start_line=285, start_column=33, end_line=285, end_column=34, law_headings=["Détermination du jour de la semaine d'une date donnée (algorithme de Sakamoto)", "Dates"]))
    pos__5 = (SourcePosition(filename="libcatala/date_fr.catala_fr", start_line=286, start_column=33, end_line=286, end_column=34, law_headings=["Détermination du jour de la semaine d'une date donnée (algorithme de Sakamoto)", "Dates"]))
    pos__6 = (SourcePosition(filename="libcatala/date_fr.catala_fr", start_line=289, start_column=7, end_line=289, end_column=8, law_headings=["Détermination du jour de la semaine d'une date donnée (algorithme de Sakamoto)", "Dates"]))
    day_number = (((((((year_number + integer_of_decimal(div(pos, year_number, Integer(4)))) - integer_of_decimal(div(pos__1, year_number, Integer(100)))) + integer_of_decimal(div(pos__2, year_number, Integer(400)))) + n_number) + acces_jour(date_donnee)) - (Integer(7) * integer_of_decimal(div(pos__6, (((((year_number + integer_of_decimal(div(pos__3, year_number, Integer(4)))) - integer_of_decimal(div(pos__4, year_number, Integer(100)))) + integer_of_decimal(div(pos__5, year_number, Integer(400)))) + n_number) + acces_jour(date_donnee)), Integer(7))))))
    jour_de_la_semaine__2 = (list_fr.nieme_element([JourDeLaSemaine(JourDeLaSemaine_Code.Lundi, Unit()), JourDeLaSemaine(JourDeLaSemaine_Code.Mardi, Unit()), JourDeLaSemaine(JourDeLaSemaine_Code.Mercredi, Unit()), JourDeLaSemaine(JourDeLaSemaine_Code.Jeudi, Unit()), JourDeLaSemaine(JourDeLaSemaine_Code.Vendredi, Unit()), JourDeLaSemaine(JourDeLaSemaine_Code.Samedi, Unit()), JourDeLaSemaine(JourDeLaSemaine_Code.Dimanche, Unit())], (day_number + Integer(1))))
    if jour_de_la_semaine__2.value is not None:
        jour_de_la_semaine__1 = (jour_de_la_semaine__2.value)
    else:
        pos__7 = (SourcePosition(filename="libcatala/date_fr.catala_fr", start_line=294, start_column=14, end_line=294, end_column=24, law_headings=["Détermination du jour de la semaine d'une date donnée (algorithme de Sakamoto)", "Dates"]))
        raise Impossible(pos__7, None)
    return jour_de_la_semaine__1
